### ISSUE TITLE
Add Page - Placings

### ISSUE THREAD

**Issue by ayahtrbl** [Marktrex/gr2_bscs3a_petconnect#21]
Paliit onti ng about textarea yung papantay siya sa other inputs
preferably like this

![image_2023-11-15_115515865](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/9f6c2156-7a02-49f0-9934-43cd36e04abc)

**Comment by AriesJ12** [comment]
yan okay na check mo nalang
