### ISSUE TITLE
Ano ung mga removed pages; para d madelete ko na

### ISSUE THREAD

**Issue by AriesJ12** [Marktrex/gr2_bscs3a_petconnect#26]

**Comment by ayahtrbl** [comment]
frontend branch
-Layout-admin-pg.html
-layout-admin-pg2.html
-layout-light.css
-layout-dark.css

**Comment by AriesJ12** [comment]
de i mean; ung mga pages na kinuha natin kay aian. lahat bayon magagamit natin?

**Comment by Marktrex** [comment]
ewan kay nyah lol

**Comment by ayahtrbl** [comment]
haup. bat aq 

dejk
im not sure kung ano halos kasi lahat nagagamit natin
