### ISSUE TITLE
missing/unfinished user pages

### ISSUE THREAD

**Issue by Marktrex** [Marktrex/gr2_bscs3a_petconnect#38]
1. On the user/index.php, I dont know what is the use of the "Join Us" button and "Get Started". Please let me know.
2. On the user/home.php, there is no login/signup option in the navbar, just the user profile immediately. what if gusto mo mag browse habang hindi naka log in diba? unless trip nyo need muna mag login ng user para ma access yung page, kindly lmk.
3. On the user/adoptpage-dog.php/adoptpage-cat.php, there is no back button, navbar, and footer.
4. On the user/donatepage.php same on the adoptpage there is no back button, navbar, and footer.
5. Also sa adoptpage, yung pag pili ng mga types of pet like breed, age. weight etc. iba yung information or laman nya compare sa admin side kapag pipili sya ng types of pets na ilalagay nya.
6. yung sa english translate hmm di ko alam paano mag scroll down para mamili ka nalang kung english, spanish or filipino.

Yun palang nakikita ko mga issues kaya pls mag reply kayo per number para alam ko nangyayari sa buong website natin ^^ <3

**Comment by AriesJ12** [comment]
1. Login/register
2. Aayusin ko later ung session management ng navbar
3/4. Nag alis ako ng footer/navbar talaga dahil hindi okay ung sa iba
5. Ayusin ko mamaya(ung about don sa pag gitna, ayusin ko later na consider ko lang is small screen mb)
6. Hinihintay ko pa non ung design ng customize dropdown(galing sa donate cat/dog)

**Comment by Marktrex** [comment]
NEW ISSUES 11/26/2023
1. sa http://localhost/petconnect/dist/user/home.php, yung navbar ay hindi buo
![Uploading issues1.png…]()

**Comment by Marktrex** [comment]
o

> NEW ISSUES 11/26/2023
> 
> 1. sa petconnect/dist/user/home, yung navbar ay hindi buo
>    ![issues1](https://private-user-images.githubusercontent.com/113119450/285637351-a95b6e97-6ad3-4465-899c-b596639e49b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA4MzksIm5iZiI6MTcwMDk5MDUzOSwicGF0aCI6Ii8xMTMxMTk0NTAvMjg1NjM3MzUxLWE5NWI2ZTk3LTZhZDMtNDQ2NS04OTljLWI1OTY2MzllNDliNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2M0MzJhY2UxMTExMzRjM2QyMTM3YWRjYzBmM2JjMTAyY2FiYWE5MjQ5YjQxNmZlM2IyMGY5MGFmNzRjNjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zNtm1kecPSBgJjhXS7DOxMTErLTV1bAY8nYWYvOTCVs)
> 2. hindi gumagana yung get started na button kahit nilagyan kona ng link sa href nya...
>    ![issues2](https://private-user-images.githubusercontent.com/113119450/285637670-45b67b62-1c77-4cc6-a050-c7ae802dac35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA4MzksIm5iZiI6MTcwMDk5MDUzOSwicGF0aCI6Ii8xMTMxMTk0NTAvMjg1NjM3NjcwLTQ1YjY3YjYyLTFjNzctNGNjNi1hMDUwLWM3YWU4MDJkYWMzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmZkM2EzM2YzZjRlZDA1NzQzMTQyMjIzNmNiZjQ4NDU2YTQwMThiZDg5MTk4NWZmYWRjNDM2NDA5NTNhNmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uHSULFWcUOXtgNpHvPEhlxcTvPgf0juWZ664oQE3YOo)\
> 3. naka misplaced mga information nung dashboard sa admin  @SIDE.
>    ![issues3](https://private-user-images.githubusercontent.com/113119450/285638086-edec8126-b210-4409-a64b-9e08d365ade9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA4MzksIm5iZiI6MTcwMDk5MDUzOSwicGF0aCI6Ii8xMTMxMTk0NTAvMjg1NjM4MDg2LWVkZWM4MTI2LWIyMTAtNDQwOS1hNjRiLTllMDhkMzY1YWRlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2RmYTNlNTUyMTc4NjJlN2ZjNjJhNjgxMDEyMjJhZGNkNmNmNzVlZDQ5MDBiMmNmYjc2MmFlZGJiYzllMzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xCsJkmSWGrg2NuVnFZRucarNy-p0mA794C4QcdiwjM4)
> 4. iba parin mga information sa pag search ng pets sa adoptpage
>    ![issues4](https://private-user-images.githubusercontent.com/113119450/285638159-cc9c158f-7d23-40a1-8133-7c368b1253ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA4MzksIm5iZiI6MTcwMDk5MDUzOSwicGF0aCI6Ii8xMTMxMTk0NTAvMjg1NjM4MTU5LWNjOWMxNThmLTdkMjMtNDBhMS04MTMzLTdjMzY4YjEyNTNlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDgzZDQ3MzRkYjFkZTYyYmU0N2JhNjQ2YzUxYTg3MDA5MjNjYTMyZmM3ZGQ0OGY1M2FiNDJlYzE5MjVhNGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BkQX1rYhq4qf6llwE3qzra1wnhLyFG4O-AJrIO6CYM4)
> 5. what does this do in the volunteer page?
>    ![issues5](https://private-user-images.githubusercontent.com/113119450/285638669-95f67976-62c7-4e68-b856-0de3288ac486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA4MzksIm5iZiI6MTcwMDk5MDUzOSwicGF0aCI6Ii8xMTMxMTk0NTAvMjg1NjM4NjY5LTk1ZjY3OTc2LTYyYzctNGU2OC1iODU2LTBkZTMyODhhYzQ4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNGEyZWNkZWFhYzc4NzlmMTQ0NWYzNzcxMmFiZGFhYzVlNWNlY2JhZGFiYjA5YTAxMGU1NGE1MDM4NTU4NWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sucb_zN88v5zAIHdraT9i-4lA9mYZk1xapoTYYj3kys)
> 6. yung book appointment di pa pala nagiging isang page, diba sabi nyo isang page nalang lahat?
>    ![issues6](https://private-user-images.githubusercontent.com/113119450/285640826-651bfcc0-738c-4a0c-a692-0174b37fae05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTA4MzksIm5iZiI6MTcwMDk5MDUzOSwicGF0aCI6Ii8xMTMxMTk0NTAvMjg1NjQwODI2LTY1MWJmY2MwLTczOGMtNGEwYy1hNjkyLTAxNzRiMzdmYWUwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNlQwOTIyMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2M5ZWQzYjNjOGQ4ZmFhMTNmODAxMzY4ODQ3MTJmNzU3YTMyNTI1YTY0NDQ2Mzg5ZGFiZWUxOTY4OTQyODQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZS1ncxqsjyp1Ta7jsrYndkxADaBJFLI0xIPAqV2OmUc)

ok na yung 2.

**Comment by Marktrex** [comment]
fixed na 2 and buttons

**Comment by ayahtrbl** [comment]
Answers on new issues (all answers ko based sa frontend)

2. get started button should linked to register page
4. alam ko napalitan mo na ata chinat moko non
5. i think para marecord sa dashboard and database kung sino mga nagvolunteer (nagbase ako sa dating page ni aian)
11. di ko gets question mo here but ito pagkaintindi ko; if ikaw ang admin siguro di mo naman need ieedit picture ni user kasi choice niya yon lols pero kayo bahala if need yon or what ilagay niyo nalang

**Comment by Marktrex** [comment]
lol 3 days ago na pala to xD sorry na busy sa intrams >_<
