### ISSUE TITLE
missing pages

### ISSUE THREAD

**Issue by ayahtrbl** [Marktrex/gr2_bscs3a_petconnect#47]
to do ulit ni nya 

- [x] admin message page
- [x] otp
- [x] forget password page
- [x] vidcall
- [x] user message page
- [x] floating message button in user view

**Comment by AriesJ12** [comment]
Sa 1 Inalis ko na un e; dko alam kay marc binabalik niya

Sa 4 dko man alam paano iaapply lols

**Comment by ayahtrbl** [comment]
> Sa 4 dko man alam paano iaapply lols

 floating message button in user view:
![Screenshot 2023-12-03 043720](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/b38d8e29-48f8-4e3f-9faf-72309be1296f)

hover:
![Screenshot 2023-12-03 043729](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/7c48fb0f-95a3-400a-80e8-c7841b7da11b)

once clicked mapupunta sa user message page

**Comment by Marktrex** [comment]
yung 1. maangas oks na

**Comment by ayahtrbl** [comment]
otp and  forget password page already done nasa additional-pages branch
