### ISSUE TITLE
How to make the Adopt Stories?

### ISSUE THREAD

**Issue by Marktrex** [Marktrex/gr2_bscs3a_petconnect#60]
1. pero first prob, paano gagawing adopted ni admin yung pet sa admindashboard
2. after ma pindot yung adopted na button kay admin, bali dadagdag ng column yung pets na pets_status
3. kung aavailable ba or adopted no
4. kapindot s-set yung pet_status  === "Adopted"
5. 1st query, tapos 2nd query, ma aadd yung info ng pets sa new Table
6. parang yung ginawa ko dati sa chat function non dalwang query yung naka set
7. para pag nag create ng account , yung isang query sa user table tas chat_user_table noon

**Comment by AriesJ12** [comment]
3 solutions:
1. may button sa admin manage users, will adopt siguro ( tapos mapupunta sa adopt page, wherein makkapag search ng pets)
2. vice versa - sa manage pets lalagay
3. completely agnostic ung adopt pets, first column nag seselect ng user; 2nd column nag seselect ng pet

**Comment by AriesJ12** [comment]
ayo tapos
