### ISSUE TITLE
last issue bago mag new year 🥳✨🎉

### ISSUE THREAD

**Issue by Marktrex** [Marktrex/gr2_bscs3a_petconnect#90]
- [x] 1. Hindi full screen yung admin/user message
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/fe22a145-9541-48e1-8089-3d37c970394d)
- [x] 2. Hindi naka align or pantay yung drop down buttons sa navbar hehehe 
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/16e92ccc-4cd3-4e9f-bee5-6d5f89e2c8cc)
- [x] 3. Translation nung About Us kahit ako na mamaya
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/fa3ee2c0-fef2-445f-8ed1-8474ef40e2a2)
- [x] 4. Yung border color light/dark mode option hindi same sa ibang page lol
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/65237e5a-651f-413e-86b4-1e9a244d4f34)
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/f268cae7-129a-457d-a237-2b7e3639e55f)
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/5ffe0f3e-9eaa-469c-9176-414ace30dbdb)
- [x] 5. Yung "About Us" na link hindi sya nagiging orange kapag nag scroll ka
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/ddec2c8c-6dc1-47f0-8b61-a294c6c667ef)
- [x] 6. Yung "homepage" mali parin dark mode colors
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/8023b462-e560-417a-b65d-d853e7404b81)
- [x] 7. Yung "Adoption Stories" wala pang dark mode
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/c3ab9c7f-5146-456e-9331-1530739d9012)
- [x] 8. Appointment Confirmation ay mali link? hindi ko to alam e
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/ab457d04-9324-495d-8477-95cad14864cc)
- [x] 9. The Admin Add Adoption function doesnt seem to work... tinry ko ipag add yung sinicchi pati yung bagong pet na nilagay ko kaso i click ko yung add to adoption ayaw parin nya gumana kahit sa database hindi nagiging isAdopted=1 yung value nung pet sa table pets. Kahit sa adoption table hindi napupunta doon yung pinag add ko
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/6725c69d-ee26-4d5c-a110-be5a4b74b20d)
- [x] 10. hindi parepareho yung kulay ng darkmode and lightmode sa mga pages.
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/ca95df26-6079-4d3a-a7a3-3c5634245edb)
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/ee139135-2969-4f8c-aa48-69319ef098db)
- [x] 11. Mga links di kopa pala nalagay lol bukas nalang
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/511a7632-ea0a-4a35-87d5-feb9f444f98e)
- [x] 12. Walang laman contact and address sa about-us.php
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/113119450/5f6ce963-0257-4666-9f38-d615ecf460d6)
- [x] 13. mga links na meron kaso walang page
Testimonials
Legal Documentation
Privacy Policy
Terms of use

**Comment by ayahtrbl** [comment]
10 done na nalagyan q na color sa branch ko

**Comment by Marktrex** [comment]
gege check ko kauwi
