### ISSUE TITLE
Fixing, debugging, etc.

### ISSUE THREAD

**Issue by ayahtrbl** [Marktrex/gr2_bscs3a_petconnect#92]
- [x] Navbar/hidden navbar color papalitan lang

- [x] Remove x and v overflow nalang if possible
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/00a260bb-3ed6-46ad-a582-31d6932b7169)

- [x] Pati yung unnecessary na navbar
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/a89452c9-f5d5-4dab-b3a9-9fadd089d2b1)

- [x] Nawala responsiveness niya holi shiet
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/f5c510c6-5b3d-4367-9cec-a362cd684d1d)

- [x] Adopt Page, may anomaly sa upper left corner
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/308ff6c2-54c9-4aa9-b783-f312972d267c)

- [x] yung hover effect wala sa homepage at adopt page
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/1ab68ddc-fc7d-4156-aca8-30e3539a2180)

- [x] pictures nalang yie
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/9786413d-06f2-41e8-a441-c83d06e65c63)

- [x] about us page need fixing
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/1158185a-e2d8-49bc-ab66-e5742cd29da4)

- [x] gawin transparent nalang to pag sa mobile view
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/93803a61-a37a-4bc9-8822-5ae0357cbd33)

- [x] yung footer di siya nag dadarkmode pag naka mobile view
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/5c03a738-ea23-46ef-889d-b0e49c98b2b2)

- [x] this
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/f5e54337-f963-455e-ac91-3e07142e3078)

- [x] di gumagana profile button sa hidden navbar sa mobile 
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/ea54820a-1df6-4b4e-8595-603ae446b19a)

- [x] walang navbar and footer yung profile page pero if prefer niyo na wala sige langs
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/128298100/97bd11f9-c550-4605-b62e-802e661b73a7)

- [x] updates sa videocall frontend
- [x] darkmode in message both sides

- [x] dark mode sa video call
- [x] dark mode sa booking successful(appointment_sucessful.php)
- [x] blurry
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/119474970/7e07a98f-96b6-4146-b5a1-ef07cef66411)

- [x] color for light admin navbar
![image](https://github.com/Marktrex/gr2_bscs3a_petconnect/assets/119474970/e3557fe8-f5b8-447b-b4b9-ef62ee1bb00c)
 

_Naka base po ito sa branch ko (nyah) name paki check nalang sila if naresolve na sila thank u_

**Comment by Marktrex** [comment]
sa 5,6,13 ok na yung edit profile wag na lagyan ng footer at navbar para maangas
